### ISSUE TITLE
Projects in the physical directory are displayed incorrectly in the drop-down list

### ISSUE THREAD

**Issue by DubZero** [minasploit/migration-facilitator#8]
When solution projects are inside physical directories
![image](https://user-images.githubusercontent.com/9574089/140904811-0cec267e-bcd2-4611-b88d-be1ab920c64a.png)

The drop-down list is looks lilke this
![image](https://user-images.githubusercontent.com/9574089/140904901-e6e0471c-6787-44e1-8349-7cbf72a83679.png)

Solution structure in IDE:
![image](https://user-images.githubusercontent.com/9574089/140905065-d84a09dd-4604-4810-b99e-d0638be1b42c.png)

**Comment by minasploit** [comment]
Can you please check what version of the plugin you're using? 

Make sure you have the latest version (v1.0.6) installed.

**Comment by DubZero** [comment]
Yes, it is 1.0.6
![image](https://user-images.githubusercontent.com/9574089/140911052-88f98fa8-5206-4d1c-9640-304172534730.png)

**Comment by minasploit** [comment]
Great. I will see to it in depth. Thanks!!

**Comment by DubZero** [comment]
Thank you, for the very useful plugin :)

**Comment by DubZero** [comment]
Testing release 1.0.7 selected value in drop-down list is correct, but
![image](https://user-images.githubusercontent.com/9574089/140983116-40b74f19-c7a1-42fc-aae1-93704e4a8610.png)
![image](https://user-images.githubusercontent.com/9574089/140983530-d60520f5-185c-44a9-a3d8-b3d7bc770194.png)
![image](https://user-images.githubusercontent.com/9574089/140983574-cac42b02-2e1d-4049-9614-7187d1df864c.png)

**if I choose a variant it doesn't work. I add to the start "scr/" and it works** 

![image](https://user-images.githubusercontent.com/9574089/140983426-24f07345-f5ae-4712-988f-29cc5526e17d.png)
![image](https://user-images.githubusercontent.com/9574089/140983805-7984740a-bce6-4582-8f77-243884b9a718.png)

**Comment by minasploit** [comment]
Ahhh, so the addition of the full path is required for dotnet to recognize it as a project... that's interesting. 

I had thought that the identification of the right project name will be enough for dotnet, but apparently, it doesn't.

I will do a quick fix for that and recommit. Thanks!

**Comment by minasploit** [comment]
@DubZero please have a look at the attached zip, and check that it works all good for you

[migration-facilitator-1.0.7.zip](https://github.com/minasploit/migration-facilitator/files/7507463/migration-facilitator-1.0.7.zip)

**Comment by DubZero** [comment]
Great! :)

Testing on 2 case

✔ when the **_src_** directory is virtual (directory nesting only exists in .sln file, but src directory does not exist)

✔ when the **_src_** directory is physical

**Comment by minasploit** [comment]
The first case might bring up some errors... 🤞 hopefully not

**Comment by minasploit** [comment]
Checked on my end. The build itself fails, hence the plugin can't circumvent that. I'll take that as a pass and push the release.

**Comment by minasploit** [comment]
Checked on my end. The build itself fails, hence the plugin can't circumvent that. I'll take that as a pass and push the release.

**Comment by minasploit** [comment]
v1.0.7 has been approved and released, fixing this issue. Thank you for all your help @DubZero
